# This task shall validate the supplied URLs with the list of known and trusted suppliers.
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: check-trusted-list
spec:
  params:
    - name: elems
      type: array
      description: array of elements which shall be checked against the list of trusted suppliers
    - name: list-url
      type: string
      description: webaddress, where the source of trusted entities is residing
  steps:
    # we need to define two steps with similar functionality, since tekton does not support arrays in script blocks
    # https://github.com/tektoncd/pipeline/issues/2374
    - name: check-trusted-list
      image: ubi9-minimal:9.1
      args: [ "$(params.elems[*])" ]
      script: |
        #!/usr/bin/env bash
        curl -s $(params.list-url) -o trusted.txt

        for elem in $@; do
          list=trusted.txt

          if [[ $elem =~ "^docker://" ]]; then
            # we only extract the registry name for the moment
            # thus you won't be able to whitelist specific repositories on i.e. dockerhub
            compare=`echo $elem | cut -d: -f2 | cut -d/ -f3`
            grep $compare $list

          elif [[ $elem =~ "^https://" ]]; then
            # we allow git sources to be specified at a toplevel
            # for other schematas adapt the code
            # https://github.com/company/projecta/projectb will be shortened to
            # https://github.com/company and compared afterwards

            compare=`echo $elem | cut -d/ -f 1-4
            grep $compare $list
          # ToDo add git ssh possibility
          else
            echo "invalid element $elem"
            return 1
          fi

          if [ $? -ne 0]; then
            echo '$compare not in list'
            return 1
          fi
          }
        done