# This task shall validate the supplied URLs with the list of known and trusted suppliers.
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: inputs-validate
spec:
  params:
    - name: source-fqdns
      type: array
      description: array of fqdns which shall be checked against the list of trusted suppliers
    - name: dest-fqdns
      type: array
      description: array of fqdns which shall be checked against the list of trusted targets

  steps:
    - name: check-inputs
      image: ubi9-minimal:9.1
      script: |
        #!/usr/bin/env bash
        curl -s https://raw.githubusercontent.com/sluetze/scs-demo/main/policy/trusted-suppliers.txt -o trusted-suppliers.txt
        curl -s https://raw.githubusercontent.com/sluetze/scs-demo/main/policy/trusted-targets.txt -o trusted-targest.txt

        function validate () {
        fqdn=$1
        list=$2

        if [[ $fqdn =~ "^docker://" ]]; then
          compare=`echo $fqdn | cut -d: -f2 | cut -d/ -f3`
          grep $compare $list

        elif [[ $fqdn =~ "^https://"]]; then
          # we allow git sources to be specified at a toplevel
          # for other schematas adapt the code
          # https://github.com/company/projecta/projectb will be shortened to
          # https://github.com/company and compared afterwards

          compare=`echo $fqdn | cut -d/ -f 1-4
          grep $compare $list
        else
          echo "invalid fqdn $fqdn"
          return 1
        fi

        if [ $? -ne 0]; then
          echo '$compare not in list'
          return 1
        fi
        }

        # ToDo

        for url in $(params.source-fqdns); do
          validate $url trusted-suppliers.txt
        done
        for url in $(params.dest-fqdns); do
          validate $url trusted-targest.txt
        done