# This task shall upload an image to quay
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: upload-image
spec:
  params:
    - name: source-fqdns
      type: array
      description: array of fqdns which shall be checked against the list of trusted suppliers
    - name: dest-fqdns
      type: array
      description: array of fqdns which shall be checked against the list of trusted targets

  steps:
    - name: check-inputs
      image: ubi9-minimal:9.1
      script: |
        #!/usr/bin/env bash
        exit 0