apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: scs-check-images
  namespace: scs-demo
spec:
  description: |
    This pipeline checks an collection of manifests according to BSI Requirements. It expects the manifests to be in the workspace
  params:
    - name: deployment-name
      type: string
      description: name of the deployment to be patched
    - name: source-git-url-manifest
      type: string
      description: url of the source git where the manifests are
    - name: source-git-revision-manifest
      type: string
      description: revision of the source manifest git
    - name: source-git-url-buildcode
      type: string
      description: url of the source git where the sourcecode for the application resides
    - name: source-git-revision-buildcode
      type: string
      description: revision of the source application git
    - name: source-registry
      type: string
      description: name of the source registry
    - name: dest-git-url-manifest
      type: string
      description: url of the dest git where the manifests are
    - name: dest-git-url-buildcode
      type: string
      description: url of the dest git where the sourcecode for the application resides
    - name: dest-registry
      type: string
      description: name of the dest registry
    - name: IMAGE
      type: string
      description: name of the image which shall be build
    - name: protection-need
      type: string
      description: Need for Protection of the Application/Environment

  tasks:
    - name: sbom-check
      taskRef:
        name: placeholder-returnzero
    - name: cve-scan
      taskRef:
        name: placeholder-returnzero
    - name: av-scan
      taskRef:
        name: placeholder-returnzero

    # SYS.1.6.A3
    - name: deprecated-base-image
      taskRef:
        name: placeholder-returnzero

    # SYS.1.6.A6
    - name: check-labels
      taskRef:
        name: placeholder-returnzero

    # SYS.1.6.A6
    - name: check-versioning
      taskRef:
        name: placeholder-returnzero

    # SYS.1.6.A8
    - name: check-for-secrets
      taskRef:
        name: placeholder-returnzero

    # SYS.1.6.A11
    # SYS.1.6.A14
    # SYS.1.6.A16
    - name: check-for-forbidden-packages
      taskRef:
        name: placeholder-returnzero

    # SYS.1.6.A16
    - name: check-for-forbidden-ports
      taskRef:
        name: placeholder-returnzero

    # SYS.1.6.A3
    # APP.4.4.A11
    - name: check-for-health-check
      taskRef:
        name: placeholder-returnzero

    # SYS.1.6.A12
    - name: check-metadata
      taskRef:
        name: placeholder-returnzero

    # SYS.1.6.A12
    - name: check-signatures
      taskRef:
        name: placeholder-returnzero