apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: scs-check-sourcecode
  namespace: scs-demo
spec:
  description: |
    This pipeline checks an collection of manifests according to BSI Requirements. It expects the manifests to be in the workspace
  params:
    - name: IMAGE
      type: string
      description: name of the image which shall be build
    - name: protection-need
      type: string
      description: Need for Protection of the Application/Environment

  tasks:
    - name: check-for-secrets
      taskRef:
        name: placeholder-returnzero
    - name: run-kube-linter
      taskRef:
        name: placeholder-returnzero
