apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: scs-check-manifests
  namespace: scs-demo
spec:
  description: |
    This pipeline checks an collection of manifests according to BSI Requirements. It expects the manifests to be in the workspace
  params:
    - name: IMAGE
      type: string
      description: name of the image which shall be build
    - name: protection-need
      type: string
      description: Need for Protection of the Application/Environment

  tasks:
    # SYS.1.6.A3
    - name: check-for-healthcheck
      taskRef:
        name: placeholder-returnzero

    # SYS.1.6.A5
    # APP.4.4.A4
    # APP.4.4.A7
    # APP.4.4.A18
    - name: check-network-policies
      taskRef:
        name: placeholder-returnzero

    # SYS.1.6.A8
    - name: check-for-secrets
      taskRef:
        name: placeholder-returnzero

    # SYS.1.6.A15
    - name: check-for-limits-requests
      taskRef:
        name: placeholder-returnzero

    # SYS.1.6.A16
    - name: check-for-forbidden-ports
      taskRef:
        name: placeholder-returnzero

    # SYS.1.6.A17
    # APP.4.4.A4
    - name: check-capabilities-and-scc
      taskRef:
        name: placeholder-returnzero

    # SYS.1.6.A19
    - name: check-usage-of-local-storage
      taskRef:
        name: placeholder-returnzero

    # SYS.1.6.A23
    - name: check-readonly-filesystem
      taskRef:
        name: placeholder-returnzero
      when:
        - input: hoch
          operator: in
          values:
            - "$(params.protection-need)"

    # SYS.1.6.A25
    - name: check-for-affinity-antiaffinity
      taskRef:
        name: placeholder-returnzero
      when:
        - input: hoch
          operator: in
          values:
            - "$(params.protection-need)"

    # SYS.1.6.A26
    - name: check-for-nodelabels
      taskRef:
        name: placeholder-returnzero
      when:
        - input: hoch
          operator: in
          values:
            - "$(params.protection-need)"

    # APP.4.4.A9
    - name: check-reason-for-serviceaccount
      taskRef:
        name: placeholder-returnzero

    # APP.4.4.A9
    - name: check-usage-of-default-serviceaccount
      taskRef:
        name: placeholder-returnzero

    # APP.4.4.A9
    - name: check-usage-of-specific-serviceaccount
      taskRef:
        name: placeholder-returnzero