apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: scs-download-from-supplier
  namespace: scs-demo
spec:
  workspaces:
    - name: image-dir
    - name: sourcecode-dir
    - name: manifest-dir
  description: |
    This pipeline checks the supplied parameters if the source is valid, downloads the artifacts and starts the security checks
  params:
    - name: deployment-name
      type: string
      description: name of the deployment to be patched
    - name: source-git-url-manifest
      type: string
      description: url of the source git where the manifests are
      default: https://github.com/sluetze/example-voting-app
      # default: NONE
      # Later it'll be NONE to skip if needed
    - name: source-git-revision-manifest
      type: string
      description: revision of the source manifest git
      default: HEAD
    - name: source-git-url-buildcode
      type: string
      description: url of the source git where the sourcecode for the application resides
      default: https://github.com/sluetze/example-voting-app
      # default: NONE
      # Later it'll be NONE to skip if needed
    - name: source-git-revision-buildcode
      type: string
      description: revision of the source application git
      default: HEAD
    - name: source-registry
      type: string
      description: name of the source registry
      default: quay.io/sluetzen/ubi9:latest
    - name: dest-git-url-manifest
      type: string
      description: url of the dest git where the manifests are
      default: github.com/sluetze/scs-dest-manifest
    - name: dest-git-url-buildcode
      type: string
      description: url of the dest git where the sourcecode for the application resides
      default: github.com/sluetze/scs-dest-buildcode
    - name: dest-registry
      type: string
      description: name of the dest registry
      default: github.com/sluetze/scs-dest-buildcode
    # muss Array sein fuer multiple Images
    - name: IMAGE
      type: string
      description: name of the image which shall be build
      default: ubi9:latest

  tasks:
    # Before we start doing anything, we validate if the sources are allowed
    # SYS.1.6.A6
    - name: check-trusted-source
      taskRef:
        name: check-trusted-list
      params:
        - name: elems
          value:
            - "$(params.source-git-url-buildcode)"
            - "$(params.source-git-url-manifest)"
            - "$(params.source-registry)"
        - name: list-url
          value: https://raw.githubusercontent.com/sluetze/scs-demo/main/policy/trusted-suppliers.txt
    - name: check-trusted-target
      taskRef:
        name: check-trusted-list
      params:
        - name: elems
          value:
            - "$(params.dest-git-url-buildcode)"
            - "$(params.dest-git-url-manifest)"
            - "$(params.dest-registry)"
        - name: list-url
          value: https://raw.githubusercontent.com/sluetze/scs-demo/main/policy/trusted-targets.txt

    # Image Flow
    - name: download-image
      taskRef:
        name: skopeo-copy
        kind: Task
      runAfter:
        - check-trusted-target
        - check-trusted-source
      params:
        - name: srcImageURL
          value: "docker://$(params.source-registry)/$(params.IMAGE)"
        - name: destImageURL
          value: dir:/$(params.IMAGE)"
      workspaces:
        - name: image-dir
          workspace: image-dir
        - name: images-url
          emptyDir: {}
    - name: start-check-downloaded-image
      taskRef:
        name: tkn
        kind: Task
      runAfter:
        - "download-image"
    - name: upload-checked-downloaded-image
      taskRef:
        name: skopeo-copy
        kind: Task
      runAfter:
        - start-check-downloaded-image
      params:
        - name: destImageURL
          value: "$(params.dest-registry)/$(params.IMAGE)"

    # SourceCode Flow
    - name: download-sourcecode
      taskRef:
        name: git-clone
        kind: Task
      runAfter:
        - check-trusted-target
        - check-trusted-source
      params:
        - name: url
          value: "$(params.source-git-url-buildcode)"
        - name: revision
          value: "$(params.source-git-revision-buildcode)"
      workspaces:
        - name: output
          workspace: sourcecode-dir
    - name: start-check-sourcecode
      taskRef:
        name: tkn
        kind: Task
      runAfter:
        - download-sourcecode
    - name: upload-sourcecode
      taskRef:
        name: git-cli
        kind: Task
      runAfter:
        - start-check-sourcecode
      params:
        - name: GIT_SCRIPT
          value: |
            git remote add downstream $(params.dest-git-url-buildcode)
            git push downstream main
      workspaces:
        - name: source
          workspace: sourcecode-dir
    - name: "build-image"
      taskRef:
        name: buildah
        kind: Task
      runAfter:
        - start-check-sourcecode
      params:
        - name: IMAGE
          value: "$(params.dest-registry)/$(params.IMAGE)"
      workspaces:
        - name: source
          workspace: sourcecode-dir

    # Manifest Flow
    # Download
    # Check
    # Upload
    - name: download-manifests
      taskRef:
        name: git-clone
        kind: Task
      runAfter:
        - check-trusted-target
        - check-trusted-source
      params:
        - name: url
          value: "$(params.source-git-url-buildcode)"
        - name: revision
          value: "$(params.source-git-revision-buildcode)"
      workspaces:
        - name: output
          workspace: manifest-dir
    - name: check-manifests
      taskRef:
        name: tkn
        kind: Task
      runAfter:
        - download-manifests
    - name: upload-manifests
      taskRef:
        name: git-cli
        kind: Task
      runAfter:
        - check-manifests
      params:
        - name: GIT_SCRIPT
          value: |
            git remote add downstream $(params.dest-git-url-buildcode)
            git push downstream main
      workspaces:
        - name: source
          workspace: sourcecode-dir
